package com.gchristensen.petfindingapp

/**
 * Class for alerts generated by user, functionality for checking if message is relevant to pet
 * */
class Message {
    /**
     * Checks if the pet is relevant to the message. For example would search the message content
     * for the pet's breed.
     * */
    fun isRelevantTo(pet: Pet): Boolean {
        TODO()
    }
}