package com.gchristensen.petfindingapp

/**
 * Class for alerts generated by user, functionality for checking if message is relevant to pet
 * */
class Message {
    val location: Location = TODO()

    /**
     * Checks if message is in range to location.
     * */
    fun inRange(otherLocation: Location, radius: Int): Boolean {
        return location.distanceTo(otherLocation) < radius
    }

    /**
     * Checks if the pet is relevant to the message. For example would search the message content
     * for the pet's breed.
     * */
    fun isRelevantTo(pet: Pet): Boolean {
        TODO()
    }

    /**
     * Checks if the pet is highly relevant to the message. Things like owner name or address are
     * considered here.
     * */
    fun isHighlyRelevantTo(pet: Pet): Boolean {
        TODO()
    }
}